server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shayhutdinovilnaz/bookservice-configurations
          search-paths:
           - '*service'
logging:
  file:
    name: /var/log/tech-credit/config-service.log