server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountDB?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=UTC
    username: root
    password: Qwerty-2
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true
  application:
    name: account-app
logging:
  level:
    org:
      hibernate:
        type: trace
  file:
    name: /var/log/tech-credit/account-service.log