spring:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    name: /var/log/tech-credit/core-service.log

displaynameconfig:
  isocodes:
    3308: ru
    3309: eng
  patterns:
    ru: Привет, |f| |l|
    eng: Hello, Mr/Ms |f| |l|
    default: Hello, Friend!