spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tech-credit?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=UTC&
    username: root
    password: Qwerty-2
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  file:
    name: /var/log/tech-credit/core-service.log
