spring:
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resource:
        token-info-uri: http://localhost:9191/oauth/check_token
      client:
        client-id: mobile
        client-secret: pin

logging:
  file:
    name: /var/log/tech-credit/core-service.log
