server:
  port: 8080
spring:
  application:
    name: authorization-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth?createDtabaseIfNotExist=true
    username: postgres
    password: root
    initialization-mode: always
    continue-on-error: true
    jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          default_schema: public
  cloud:
    config:
      enabled: false
logging:
  level:
    org:
      hibernate:
        type: trace
